### PR TITLE
Add support for Intel R200 camera

### PR DESCRIPTION
**Pull request by mattcurfman**
This pull request adds support for the Intel R200 camera in turtlebot_description and turtlebot_bringup, enabling use of 'export TURTLEBOT_3D_SENSOR=r200' when using the RealSense camera node at http://wiki.ros.org/RealSense.

### CODE REVIEW

**Comment by tfoote** [comment]
Overall this looks good. We should hold this and add a runtime dependency onto the driver packages when they're released. 

Also this has the R200 mounted in the URDF. Is there directions for mounting the r200 in the right place?

**Comment by ghindman** [comment]
realsense_navigation package dependency has been merged

**Comment by mattcurfman** [comment]
@ghindman please send me a note when the package for realsense_navigation is released as a ROS package, with librealsense support, then I will augment this PR with the runtime dependency. Thx!

**Comment by tfoote** [comment]
librealsense and realsense_camera I think are ready now.

**Comment by ghindman** [comment]
This PR will require some modification once https://github.com/turtlebot/turtlebot_apps/pull/152 lands - we'd like to land them sequentially.

**Comment by kevincwells** [comment]
Update: This PR has been trumped by https://github.com/turtlebot/turtlebot/pull/229, which includes these changes and several improvements and modifications.

**Comment by mattcurfman** [comment]
Thanks, Kevin.  I'll close this PR.

**Pull request closed without merging**
