### PR TITLE
fix build so it doesn't overwrite user's env vars TURTLEBOT_BASE etc

### PR DESCRIPTION
**Pull request by PaulBouchier**
env hooks was getting built into what's run by setup.bash with the result that TURTLEBOT_BASE and TURTLEBOT_SERIAL_PORT overwrite the user's environment variables for these settings. Deleted that setup.

### CODE REVIEW

**Comment by kentsommer** [comment]
This was actually intended (https://github.com/turtlebot/turtlebot_apps/issues/104). That being said, I need to have a discussion with @stonier about the best way to deal with the fact that people will have different bases which in turn changes what TUTLEBOT_BASE and TURTLEBOT_SERIAL_PORT should be.

**Comment by stonier** [comment]
The ros environment hooks are there to provide sane defaults and an easy way of introspecting what is available (e.g. `env | grep TURTLE`).

To override them, it's just a matter of determing _where_ it insert the overrides. Key difference to what has gone before is that the overrides should be **after** sourcing `setup.bash`, not **before**.

I've updated the [wiki](http://wiki.ros.org/turtlebot/Tutorials/indigo/Create%20Base) page to reflect this properly and also included a script that we use. Will that approach work for you Paul?

**Comment by stonier** [comment]
@kentsommer One thing we could do to improve the robustness is add checks in the environment hooks. If the variable is already defined, don't redefine it.

Then folks like Paul can set the environment variables before or after.

**Comment by stonier** [comment]
Closing this, we'll pursue it in #153.

**Pull request closed without merging**
