### PR TITLE
Adds capabilities support

### PR DESCRIPTION
**Pull request by bit-pirate**
Adds:
- Launchers & configs
- turtlebot_capabilties (moved in from https://github.com/osrf/turtlebot2_capabilities)
- rosinstaller for capabilities

To test:
- Install and compile all required sources using turtlebot/turtlebot_capabilities.rosinstall
- roslaunch turtlebot_bringup app_manager_with_capabilities.launch --screen
- rqt_capabilities
- start mobile base capability (right click on capability-> start)
- roslaunch kobuki_keyop keyop.launch

### CODE REVIEW

**Comment by bit-pirate** [comment]
@stonier please check and merge.

**Comment by stonier** [comment]
Not feeling brave enough to make turtlebot capabilities implicit yet? Talking about the launchers primarily - what is recommendation for the long term bringup launcher? 

Do we drop minimal.launch and just use what is effectively the app_manager and capability server?

Does app_manager_with_capabilities.launch need to reference capabilities explicitly? i.e. implicitly understand that it uses a capability server underneath. Is there a use case for an app manager without the capability server?

**Comment by stonier** [comment]
Purpose behind my comment - what should we be thinking of presenting to users for igloo?

Merging for now - seems ok to work with.

**Comment by bit-pirate** [comment]
> Not feeling brave enough to make turtlebot capabilities implicit yet? 

Brave enough I would be, but it might not be the smartest choice. :-)

First, the whole capability development hasn't settle in yet, so I don't think it is a good time to make it the default.

Second, as we discussed recently, throwing new ROS & TB users into the cold water of (r)apps and caps might be quite though for them. Hence, I'd like to give them the options of using the TB the _old school_ way with normal launchers and doing it _new school_ using apps and caps.

Regarding the development plan, I was thinking about supporting both `minimal.launch` and `app_manager_with_capabilities.launch` during Igloo. Additonally I'd like to drop `minimal_with_app_manager.launch` before the Igloo releases and use `app_manager_with_capabilities.launch` as its replacement.

@stonier @wjwoodward  @jihoonl Thoughts?

**Pull request merged**
