### PR TITLE
resolve namespace conflict

### PR DESCRIPTION
**Pull request by theRichu**

### CODE REVIEW

**Comment by jihoonl** [comment]
@corot who is in charge of these parameters are currently in holiday. We will review this when he comes back. 

resolving the naming conflict with local name-spacing looks correct to me. :)

**Comment by bit-pirate** [comment]
Does this mean the current setup is broken? If that is the case, we should fix it earlier.

**Comment by jihoonl** [comment]
No it does not mean it is broken. I think that configuration is useful to resolve one ros core'd multirobot namespacing issue. I would like to wait for Jorge because I don't know about mux configuration. Also it might have conflict with app manager framework.(with a little chance)

**Comment by bit-pirate** [comment]
Alright. Let's put this on hold until Jorge comes back.

**Comment by corot** [comment]
Thanks!
I made slightly different, but equivalent changes

**Pull request closed without merging**
