### PR TITLE
Roomba support

### PR DESCRIPTION
**Pull request by lukacu**
I have been trying to use the new groovy turtlebot packages with iRobot Roomba recently and found out that some XML files are missing in order to get the minimal.launch to run. For now I have simply copied the create files and renamed them appropriately and this works (with some adjustment to other packages in other repositories ... I will request merge there as well). I think this is the cleanest way to enable Roomba support that already exists in the python driver and I hope it will be accepted as Roomba support is very important for European turtlebot users.

### CODE REVIEW

**Comment by bit-pirate** [comment]
To put it upfront, we haven't been working much on the create and roomba support, since we have been focusing on getting turtlebot 2 (with Kobuki) working. So thanks for your help in improving roomba and create support!

So looking at your request, if you only copied the create files and didn't actually change parameters etc., is it actually necessary to add extra files?

**Comment by stonier** [comment]
I talked with Melonee yesterday, and it's been prioritised to get this working for 2.0. Clearpath will help on it, but please feel free to submit pull requests lukacu. Most of the infra should be there, probably just small things to get it working runtime. The python driver needs some groovy bugfixes for roslib->rosgraph changes as well.

**Comment by stonier** [comment]
Marcus - yeah it is. It's using args to reference these files by filename. Maybe symlinks could also work - not sure if git stores symlinks though.

**Comment by bit-pirate** [comment]
But where do we actually need different things for roomba? I see the case, when it comes to a different visualisation, but there is no mesh or different urdf for the roomba (if I checked correctly).

As I see it now, there is no change between create and roomba ...

**Comment by tfoote** [comment]
For clarity the high priority is to get the Create working.  And try not to
regress roomba compatability.  In general they mostly interact the same and
the driver supports both.

**Comment by lukacu** [comment]
Yes, the files are just copied at the moment, this seemed the easiest fix because I can now just set the TURTLEBOT_BASE envvar to roomba and everything works. Other fixes would require changing launch files and that would probably break something else. I do not mind if this is solved in some other way ...

**Comment by stonier** [comment]
Also eae4ea8eeb7c7d65aeceb9352255d17454a84d07

I replaced exact copies with git symlinks to allow roomba to benefit from updates to the create files.

Tested ok, just waiting on making sure it goes through the debian packaging ok (should be fine). Lukacu, reopen this if it does prove to be a problem.

**Pull request merged**
