### PR TITLE
Remove concert reference to mobile_base.launch

### PR DESCRIPTION
**Pull request by kevincwells**
Take out the reference to the now-removed mobile_base.launch layer.

### CODE REVIEW

**Comment by kevincwells** [comment]
Ah, sorry, just saw your comment on #239 about restoring the file and marking it deprecated.  I can include that in this PR.

**Comment by tfoote** [comment]
Adding the deprecation message would be great to add here.

**Comment by kevincwells** [comment]
Believe that should do it.

**Comment by tfoote** [comment]
Thanks that looks good.

**Pull request merged**
