### PR TITLE
Fixed turtlebot.launch file used by upstart scripts

### PR DESCRIPTION
**Pull request by abencz**
Removed obsolete argument and fixed path for minimal.launch.

### CODE REVIEW

**Comment by LucidOne** [comment]
I would prefer removing the entire upstart directory and use the generic ROS version.
https://github.com/TurtleBot-Mfg/ros-system-daemon-groovy

**Comment by stonier** [comment]
I think Bill's moving towards a good system solution here. 

Bill - do you have anywhere documented where you discuss the reasons for moving away from upstart to rosctl?

**Comment by LucidOne** [comment]
On 01/09/2013 09:27 PM, Daniel Stonier wrote:

> I think Bill's moving towards a good system solution here. 
> 
> Bill - do you have anywhere documented where you discuss the reasons for moving away from upstart to rosctl?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/turtlebot/turtlebot/pull/48#issuecomment-12077885

rosctl replaces turtlebot-start and turtlebot-stop
Our approach still uses upstart, but it is slightly more advanced usage.

I'll get the documentation done asap. I'm going to put it on ros.org
despite the fact that it is not a ROS package as we are
going to iterate towards bloom integration.

**Comment by tfoote** [comment]
It's fine to document things on ros.org that are not directly ros related
but are used tightly by ros users.

**Comment by tfoote** [comment]
This would also probably be something good to circulate to ros-users for
review/feedback for the next generation.

**Comment by LucidOne** [comment]
Basic docs now available in the README.md and we will work towards integrating documentation into ros.org

We will work on putting together a proposed list of best practices for running ros at the system level for review by ros-users, however this may take a few weeks.

**Pull request merged**
