### PR TITLE
Load any calibration files during create bringup

### PR DESCRIPTION
**Pull request by kbogert**
Load any available calibration files for the attached Create during bringup.  See the following pull request for more information:  https://github.com/turtlebot/turtlebot_create/pull/14

Note, this pull request depends on that one, please don't apply until it is accepted.

### CODE REVIEW

**Comment by bit-pirate** [comment]
This addition assumes everyone would like to use this calibration. Is this given? Could that be a problem for other users?

PS: Requires PR https://github.com/turtlebot/turtlebot_create/pull/14/files to be merged.

**Comment by kbogert** [comment]
Probably not, especially if they already have their own solutions or only have one turtlebot.  However, I've designed the calibration load script to exit once the turtlebot has received its first velocity command.  This should hopefully cause no noticeable issues for anyone not using calibration files.

Note that the calibration patch will also attempt to find a file based on the serial <-> usb converter's serial number, so it could conceivably be useful for anyone with a turtlebot 1.

**Comment by jihoonl** [comment]
Looks good addition for me. I am merging this. Please raise issue if this cause a problem.

**Comment by jihoonl** [comment]
Also now in indigo.

**Pull request merged**
