### PR TITLE
fix renamed files for battery info on Ubuntu 12.04.3 LTS - Kernel 3.8

### PR DESCRIPTION
**Pull request by rk4an**

### CODE REVIEW

**Comment by tfoote** [comment]
+1 partial fix for #102

**Comment by bit-pirate** [comment]
Does this work for other Ubuntu versions as well? E.g. 12.04._03_ is only available on 32bit. Maybe we need a script to detect the Ubuntu version and apply the correct paths and filenames.

**Comment by rk4an** [comment]
Not tested on other version of Ubuntu sorry. Yes we can improve the script by checking more efficiently /proc/acpi/power_supply directory, then /sys/class/power_supply, then file in this directory.

An other idea is to install acpi/acpitool package and parse the output

**Comment by yhju** [comment]
+1 in using acpi/acpitool package. It may give more consistent output in various versions of Ubuntu.

**Comment by stonier** [comment]
@jorge what are your thoughts on this?

**Comment by corot** [comment]
Is in my todo list waiting for an opportunity. I'll do on Monday.

On acpi/acpitool: I did a fast googeling and failed to find an API, so I suppose @rk4an's idea is to execute acpitool and recover its text output, right?

**Comment by tfoote** [comment]
When first doing this I think I looked at using acpi/acpitool and wasn't able to get what I wanted as cleanly.  The abstraction might be worth it, but it might end up adding as much complexity as simply catching the known cases.

**Comment by corot** [comment]
Right, so I think by now is ok to parse the BAT0 text file. In the future
would be cool to extend this package to provide extra house-keeping laptop
data, as CPU/RAM load, CPU temperature, etc, and maybe then will be time to
use acpi/acpitool.

2013/10/25 Tully Foote notifications@github.com

**Comment by rk4an** [comment]
@corot yes the second idea was to execute acpitool and get output. But maybe some data missing with this solution

**Comment by jronald** [comment]
Say, it seems that this change has not made it into the Groovy or Hydro general releases yet - at least not the 12.04 LTS repositories.

**Comment by stonier** [comment]
Made an isolated release of this stack only. Look for version 2.2.3 on hydro shadow-fixed shortly.

We're not making any further releases for groovy at this point in time.

**Comment by jronald** [comment]
Thanks!! I'm currently away from my robots until Thursday night.  Is there
a wiki article or such in regard to adding in the shadow-fixed repositories?

**Comment by stonier** [comment]
Edit `/etc/apt/sources.list.d/ros-latest.list` (or wherever you have the repo listed) so it looks like the following:

```
# deb http://packages.ros.org/ros/ubuntu precise main
deb http://packages.ros.org/ros-shadow-fixed/ubuntu precise main
```

It's not building yet because of a failure downstream (openni-camera). You can watch progress of the builds and which versions are in which repo (building/shadow-fixed/public) at: http://www.ros.org/debbuild/hydro.html

**Comment by jronald** [comment]
Thanks for your help.

It looks like the turtlebot package is still not building because of a
failure downstream (openni-camera).

**Pull request merged**
