### PR TITLE
3dsensor configuration via env hook.

### PR DESCRIPTION
**Pull request by jihoonl**
To address #171.

Shall we change the [default of 3d sensor env-hook](https://github.com/turtlebot/turtlebot/blob/indigo/turtlebot_bringup/env-hooks/25.turtlebot.sh.em#L13) to asus?

### CODE REVIEW

**Comment by tfoote** [comment]
We'll need to keep the kinect as the default for backwards compatibility. Otherwise many people would break when they update. On new turtlebots distributed we should however set that flag on preinstalled machines.

**Comment by stonier** [comment]
@tfoote - when we officially annouce turtlebot on indigo (should be within the month), might we announe that pre-indigo supports Kinect as default and indigo supports Asus as default?

This way there is some compromise for legacy users - I imagine many of these haven't upgraded to indigo yet. And these users are experienced with the turtlebot environment and so should handle the change with little concern.

New users on the other hand - many of them actually buy turtlebots without the laptops and others often hook up the bots to their pc's for some testing. These will be the ones who will get confused with the wrongly configured 3d sensor. As they are less experienced with the whole environment, I'm more inclined to help them than the veterans.

**Comment by tfoote** [comment]
That's true, since we haven't officially released for indigo we have some
more leeway. We'll just want to make a migration guide for the Indigo
upgrade.

**Comment by stonier** [comment]
yep :neckbeard:

**Comment by jihoonl** [comment]
Now asus is default in env-hook

**Comment by jihoonl** [comment]
New PR will be created with new configuration of Asus Xtion Pro.

**Comment by lukacu** [comment]
Hello, so will the 3dsensor_config branch get merged anytime soon? We are still using the old Kinect in a course on mobile robotics, I can confirm that this branch does work out of the box, while the master branch does not.

**Comment by jihoonl** [comment]
@lukacu 

https://github.com/turtlebot/turtlebot/pull/194 should have addressed your problem

**Comment by lukacu** [comment]
Ok, thank you. So the changes are already in the master branch, but not yet in the package repository? I forgot to mention that we have not tested the master branch recently, just the deb package.

**Pull request closed without merging**
