### PR TITLE
add depth argument to configure scan_processing. With this configuration...

### LINKED ISSUE #123: Some topics created by 3dsensor.launch produce no messages
Under Groovy, 3dsensor.launch created a large number of topics, any of which could be visualized in rviz.  Under Hydro, more or less the same topics are created, but only a subset of topics ever produce any messages.  For example the /scan topic is silent.   The mix of working topics changes based on depth registration.  For example /scan works if the file is launched like this,

`3dsensor.launch depth_registration:=false`

but then some other topics stop publishing.

I'm not sure if this is the intended behavior, but it will certainly be confusing for the intended Turtlebot audience. 

Here is a ROS Answers thread where the issue is discussed:

http://answers.ros.org/question/112391/nothing-published-to-scan-under-hydro/

### PR DESCRIPTION
**Pull request by jihoonl**
... scan works for both depth_regratation false and true

It is related with #128 and it resolved #123

scan topic name configuration topic naming using argument existed in groovy but somehow it disappeared in hydro.

_Groovy_
https://github.com/turtlebot/turtlebot/blob/groovy/turtlebot_bringup/launch/3dsensor.launch#L24-L26
https://github.com/turtlebot/turtlebot/blob/groovy/turtlebot_bringup/launch/3dsensor.launch#L83-L90

Hydro : 
https://github.com/turtlebot/turtlebot/blob/hydro/turtlebot_bringup/launch/3dsensor.launch#L22-L23
https://github.com/turtlebot/turtlebot/blob/hydro/turtlebot_bringup/launch/3dsensor.launch#L59-L73

### CODE REVIEW

**Comment by tfoote** [comment]
+1

**Comment by bit-pirate** [comment]
Looks good.

**Comment by bit-pirate** [comment]
@jihoonl please also add this to hydro-devel.

**Comment by jihoonl** [comment]
Cherry picked. https://github.com/turtlebot/turtlebot/commit/3e32933c829e308600707a9f971334d13d1cbe19

**Pull request merged**
