### PR TITLE
Add xacro xml namespace prefix to macro usages

### PR DESCRIPTION
**Pull request by corot**
Deprecated: xacro tag 'kobuki' w/o 'xacro:' xml namespace prefix (will be forbidden in Noetic)

### CODE REVIEW

**Comment by corot** [comment]
@emersonknapp, can you take a fast look at this PR?

Btw, do you plan to complete your ROS2 porting?

**Review by emersonknapp — APPROVED** [review]
This LGTM, but I don't have write access to these repos so I can't merge or anything

**Comment by emersonknapp** [comment]
@corot  I am using a turtlebot2 base and standoffs with ROS2 and I'm only interested in the turtlebot_description package, so that's all I've ported, I have no plan to port the rest of the packages - I was kind of thinking about separating turtlebot_description into a separate repository.

I'd be happy to submit a PR to this repo with only that package ported, but I can't create the necessary target `ros2` branch, I'd need a repo owner to do it

**Comment by corot** [comment]
Thanks for reviewing.
So together with https://github.com/ros2/turtlebot2_demo, you only need turtlebot_description to run TB2 on ROS2? Then maybe you should add your port there? Cause sure, I can make a ros2 branch here, but it will containtain esentially melodic plus your ported turtlebot_description... what can be rather confusing. I'm thinking, don't you need to port also turtlebot_bringup?

**Comment by emersonknapp** [comment]
I only need the driver `kobuki_node` and the description packages for urdfs. I find that "bringup" packages are usually useless because they make too many assumptions and bring in implicit dependencies. You can see my ROS2 launchfile here for the Turtlebot2 https://github.com/emersonknapp/robot_stack/blob/master/robot_stack/launch/robot_stack.launch.py

Edit: To be more explicit: here is what I use in my robot's urdf (https://github.com/emersonknapp/robot_stack/blob/master/robot_stack/urdf/homey.urdf.xacro)

```
  <xacro:include filename="$(find turtlebot_description)/urdf/turtlebot_common_library.urdf.xacro" />
  <xacro:include filename="$(find kobuki_description)/urdf/kobuki.urdf.xacro" />
  <xacro:include filename="$(find turtlebot_description)/urdf/stacks/hexagons.urdf.xacro"/>
```

**Comment by corot** [comment]
Thanks! This will help me.

Still, u need a place to gather launchers and configuration files... but on https://github.com/ros2/turtlebot2_demo there's none yet

**Comment by emersonknapp** [comment]
My perspective is that it's best to keep default configuration as close to the individual components as possible. Then the bringup package is basically a folder of example launchfiles. Thinking about it, that's probably useful in and of itself. I'm sure there are other users who get more benefit out of it than I do. I'm always customizing the robot, so the "out of the box" solution doesn't usually work.

**Pull request merged**
